name: tensors
channels:
  - conda-forge
dependencies:
  - python==3.11.*
  - cudatoolkit=11.8.0
  - requests
  - pymc
  - pip
  - pip:
    - nvidia-cudnn-cu11==8.6.0.163
    - --find-links https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
    - "jax[cuda12_pip]" 
    - numpyro
    - blackjax  
  - dask
  - pandas
  - numpy
  - scikit-learn
  - pyyaml
  - pytest
  - coverage
  - pylint
  - pytest-cov
  - flake8