name: uncertainty
channels:
  - conda-forge
dependencies:
  - python==3.11.*
  - requests
  - pymc
  - pip
  - pip:
    - --find-links https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
    - "jax[cuda12_pip]" 
    - numpyro
    - blackjax  
  - dask
  - pandas
  - numpy
  - scikit-learn
  - pyyaml
  - pytest
  - coverage
  - pylint
  - pytest-cov
  - flake8