name: tensors
channels:
  - conda-forge
dependencies:
  - python==3.11.*
  - cudatoolkit=11.8.0
  - pip
  - pip:
    - nvidia-cudnn-cu11==8.6.0.163
    - tensorflow==2.13.*
    - "dask[complete]"
    - scikit-learn
    - numpy
    - pandas
    - jupyterlab>=4.0.*
    - pyyaml
    - requests>=2.31.*
    - pytest
    - coverage
    - pylint
    - pytest-cov
    - flake8