name: space
channels:
  - conda-forge
  - rapidsai
dependencies:
  - python==3.10.*
  - cudatoolkit=11.8.0
  - jupyterlab==4.0.*
  - pyyaml==6.0.*
  - cuspatial
  - cudf
  - cuml
  - pip
  - pip:
    - nvidia-cudnn-cu11==8.6.0.163
    - dask[complete]
    - requests>=2.31.*
    - pytest>=7.4.*
    - coverage>=7.2.*
    - pylint>=2.17.*
    - pytest-cov>=4.1.*
    - flake8>=6.0.*