name: space
channels:
  - rapidsai
  - conda-forge
  - nvidia
dependencies:
  - python==3.10.*
  - cuda-version=12.0
  - cudf
  - cuml
  - cuspatial
  - cuproj
  - jupyterlab==4.0.*
  - pyyaml==6.0.*
  - dask
  - requests>=2.31.*
  - pytest>=7.4.*
  - coverage>=7.2.*
  - pylint>=2.17.*
  - pytest-cov>=4.1.*
  - flake8>=6.0.*