name: tensors
channels:
  - anaconda
dependencies:
  - python==3.11.*
  - dask>=2023.6.*
  - pandas>=2.0.*
  - numpy>=1.24.*
  - scikit-learn>=1.3.*
  - pyyaml
  - jupyterlab
  - requests>=2.31.*
  - pytest>=7.4.*
  - coverage>=7.2.*
  - pylint>=2.17.*
  - pytest-cov>=4.1.*
  - flake8>=6.0.*